# Generated by Django 4.0 on 2022-02-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='harare', max_length=100),
            preserve_default=False,
        ),
    ]
