# Generated by Django 4.0 on 2022-02-02 11:34

from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_post_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=market.models.upload_gallery_image)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.post')),
            ],
        ),
    ]
