# Generated by Django 4.0 on 2022-02-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.post'),
        ),
    ]
