# Generated by Django 4.0 on 2022-02-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_image_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_name',
            new_name='post',
        ),
    ]
